bsuir_individual_plan_homepage:
    path:     /
    defaults: { _controller: BSUIRIndividualPlanBundle:IndividualPlans:index }

professors_register:
    path:     /register
    defaults: { _controller: BSUIRIndividualPlanBundle:Professors:register }
professors_login:
    path:     /login
    defaults: { _controller: BSUIRIndividualPlanBundle:Security:login }
    methods:  [GET, POST]
professors_login_check:
    path: /login_check
professors_logout:
    path: /logout

individual_plan_index:
    path:   /individual-plan
    defaults: { _controller: BSUIRIndividualPlanBundle:IndividualPlans:index }
    methods:  [GET, POST]
individual_plan_create:
    path:   /individual-plan/create
    defaults: { _controller: BSUIRIndividualPlanBundle:IndividualPlans:create }
    methods:  [GET, POST]
individual_plan_update:
    path:   /individual-plan/update/{ip_id}
    defaults: { _controller: BSUIRIndividualPlanBundle:IndividualPlans:update }
    methods:  [GET, POST]
    requirements:
        ip_id: \d+
individual_plan_remove:
    path:   /individual-plan/remove/{ip_id}
    defaults: { _controller: BSUIRIndividualPlanBundle:IndividualPlans:remove }
    methods:  [GET]
    requirements:
        ip_id: \d+
individual_plan_print:
    path:   /individual-plan/print/{ip_id}
    defaults: { _controller: BSUIRIndividualPlanBundle:IndividualPlans:print }
    methods:  [GET]
    requirements:
        ip_id: \d+

educational_methodical_work_index:
    path: /educational-methodical-work
    defaults: { _controller: BSUIRIndividualPlanBundle:EducationalMethodicalWork:index }
educational_methodical_work_create:
    path: /educational-methodical-work/create/{ip_id}
    defaults: { _controller: BSUIRIndividualPlanBundle:EducationalMethodicalWork:create }
    methods:  [GET, POST]
    requirements:
        ip_id: \d+
educational_methodical_work_update:
    path: /educational-methodical-work/update/{emw_id}
    defaults: { _controller: BSUIRIndividualPlanBundle:EducationalMethodicalWork:update }
    methods:  [GET, POST]
    requirements:
        emw_id: \d+
educational_methodical_work_remove:
    path: /educational-methodical-work/remove/{emw_id}
    defaults: { _controller: BSUIRIndividualPlanBundle:EducationalMethodicalWork:remove }
    methods:  [GET]
    requirements:
        emw_id: \d+
educational_methodical_work_print:
    path: /educational-methodical-work/print/{emw_id}
    defaults: { _controller: BSUIRIndividualPlanBundle:EducationalMethodicalWork:print }
    methods:  [GET]
    requirements:
        emw_id: \d+

educational_methodical_items_create:
    path: /educational-methodical-items/create/{emw_id}
    defaults: { _controller: BSUIRIndividualPlanBundle:EducationalMethodicalItems:create }
    methods:  [GET, POST]
    requirements:
        emw_id: \d+
educational_methodical_items_update:
    path: /educational-methodical-items/update/{emi_id}
    defaults: { _controller: BSUIRIndividualPlanBundle:EducationalMethodicalItems:update }
    methods:  [GET, POST]
    requirements:
        emi_id: \d+
educational_methodical_items_remove:
    path: /educational-methodical-items/remove/{emi_id}
    defaults: { _controller: BSUIRIndividualPlanBundle:EducationalMethodicalItems:remove }
    methods:  [GET]
    requirements:
        emi_id: \d+
        
scientific_work_index:
    path: /scientific-work
    defaults: { _controller: BSUIRIndividualPlanBundle:ScientificWork:index }
scientific_work_create:
    path: /scientific-work/create/{ip_id}
    defaults: { _controller: BSUIRIndividualPlanBundle:ScientificWork:create }
    methods:  [GET, POST]
    requirements:
        ip_id: \d+
scientific_work_update:
    path: /scientific-work/update/{sw_id}
    defaults: { _controller: BSUIRIndividualPlanBundle:ScientificWork:update }
    methods:  [GET, POST]
    requirements:
        sw_id: \d+
scientific_work_remove:
    path: /scientific-work/remove/{sw_id}
    defaults: { _controller: BSUIRIndividualPlanBundle:ScientificWork:remove }
    methods:  [GET]
    requirements:
        sw_id: \d+
scientific_work_print:
    path: /scientific-work/print/{sw_id}
    defaults: { _controller: BSUIRIndividualPlanBundle:ScientificWork:print }
    methods:  [GET]
    requirements:
        sw_id: \d+
        
scientific_items_create:
    path: /scientific-items/create/{sw_id}
    defaults: { _controller: BSUIRIndividualPlanBundle:ScientificItems:create }
    methods:  [GET, POST]
    requirements:
        sw_id: \d+
scientific_items_update:
    path: /scientific-items/update/{si_id}
    defaults: { _controller: BSUIRIndividualPlanBundle:ScientificItems:update }
    methods:  [GET, POST]
    requirements:
        si_id: \d+
scientific_items_remove:
    path: /scientific-items/remove/{si_id}
    defaults: { _controller: BSUIRIndividualPlanBundle:ScientificItems:remove }
    methods:  [GET]
    requirements:
        si_id: \d+

other_work_index:
    path: /other-work
    defaults: { _controller: BSUIRIndividualPlanBundle:OtherWork:index }
other_work_create:
    path: /other-work/create/{ip_id}
    defaults: { _controller: BSUIRIndividualPlanBundle:OtherWork:create }
    methods:  [GET, POST]
    requirements:
        ip_id: \d+
other_work_update:
    path: /other-work/update/{ow_id}
    defaults: { _controller: BSUIRIndividualPlanBundle:OtherWork:update }
    methods:  [GET, POST]
    requirements:
        ow_id: \d+
other_work_remove:
    path: /other-work/remove/{ow_id}
    defaults: { _controller: BSUIRIndividualPlanBundle:OtherWork:remove }
    methods:  [GET]
    requirements:
        ow_id: \d+
other_work_print:
    path: /other-work/print/{ow_id}
    defaults: { _controller: BSUIRIndividualPlanBundle:OtherWork:print }
    methods:  [GET, POST]
    requirements:
        ow_id: \d+
        
other_items_create:
    path: /other-items/create/{ow_id}
    defaults: { _controller: BSUIRIndividualPlanBundle:OtherItems:create }
    methods:  [GET, POST]
    requirements:
        ow_id: \d+
other_items_update:
    path: /other-items/update/{oi_id}
    defaults: { _controller: BSUIRIndividualPlanBundle:OtherItems:update }
    methods:  [GET, POST]
    requirements:
        oi_id: \d+
other_items_remove:
    path: /other-items/remove/{oi_id}
    defaults: { _controller: BSUIRIndividualPlanBundle:OtherItems:remove }
    methods:  [GET]
    requirements:
        oi_id: \d+
        
education_work_plan_create:
    path: /education-work-plan/create/{ip_id}
    defaults: { _controller: BSUIRIndividualPlanBundle:EducationWorkPlan:create }
    methods:  [GET, POST]
    requirements:
        ip_id: \d+
education_work_plan_update:
    path: /education-work-plan/update/{ewp_id}
    defaults: { _controller: BSUIRIndividualPlanBundle:EducationWorkPlan:update }
    methods:  [GET, POST]
    requirements:
        ewp_id: \d+
education_work_plan_remove:
    path: /education-work-plan/remove/{ewp_id}
    defaults: { _controller: BSUIRIndividualPlanBundle:EducationWorkPlan:remove }
    methods:  [GET]
    requirements:
        ewp_id: \d+
education_work_plan_print:
    path: /education-work-plan/print/{ewp_id}
    defaults: { _controller: BSUIRIndividualPlanBundle:EducationWorkPlan:print }
    methods:  [GET]
    requirements:
        ewp_id: \d+
        
education_work_plan_items_create:
    path: /education-work-plan-items/create/{ewp_id}
    defaults: { _controller: BSUIRIndividualPlanBundle:EducationWorkPlanItems:create }
    methods:  [GET, POST]
    requirements:
        ewp_id: \d+
education_work_plan_items_update:
    path: /education-work-plan-items/update/{ewpi_id}
    defaults: { _controller: BSUIRIndividualPlanBundle:EducationWorkPlanItems:update }
    methods:  [GET, POST]
    requirements:
        ewpi_id: \d+
education_work_plan_items_remove:
    path: /education-work-plan-items/remove/{ewpi_id}
    defaults: { _controller: BSUIRIndividualPlanBundle:EducationWorkPlanItems:remove }
    methods:  [GET]
    requirements:
        ewpi_id: \d+
education_work_plan_items_print:
    path: /education-work-plan-items/print/{ewpi_id}
    defaults: { _controller: BSUIRIndividualPlanBundle:EducationWorkPlanItems:print }
    methods:  [GET]
    requirements:
        ewpi_id: \d+
        
education_work_execution_create:
    path: /education-work-execution/create/{ip_id}
    defaults: { _controller: BSUIRIndividualPlanBundle:EducationWorkExecution:create }
    methods:  [GET, POST]
    requirements:
        ip_id: \d+
education_work_execution_update:
    path: /education-work-execution/update/{ewe_id}
    defaults: { _controller: BSUIRIndividualPlanBundle:EducationWorkExecution:update }
    methods:  [GET, POST]
    requirements:
        ewe_id: \d+
education_work_execution_remove:
    path: /education-work-execution/remove/{ewe_id}
    defaults: { _controller: BSUIRIndividualPlanBundle:EducationWorkExecution:remove }
    methods:  [GET]
    requirements:
        ewe_id: \d+
education_work_execution_print:
    path: /education-work-execution/print/{ewe_id}
    defaults: { _controller: BSUIRIndividualPlanBundle:EducationWorkExecution:print }
    methods:  [GET]
    requirements:
        ewe_id: \d+