bsuir_individual_plan_homepage:
    path:     /
    defaults: { _controller: BSUIRIndividualPlanBundle:Dashboard:index }

professors_register:
    path:     /register
    defaults: { _controller: BSUIRIndividualPlanBundle:Professors:register }
professors_login:
    path:     /login
    defaults: { _controller: BSUIRIndividualPlanBundle:Security:login }
    methods:  [GET, POST]
professors_login_check:
    path: /login_check
professors_logout:
    path: /logout

individual_plan_index:
  path:   /individual-plan
  defaults: { _controller: BSUIRIndividualPlanBundle:IndividualPlans:index }
  methods:  [GET, POST]
individual_plan_create:
  path:   /individual-plan/create
  defaults: { _controller: BSUIRIndividualPlanBundle:IndividualPlans:create }
  methods:  [GET, POST]
individual_plan_update:
  path:   /individual-plan/update/{ip_id}
  defaults: { _controller: BSUIRIndividualPlanBundle:IndividualPlans:update }
  methods:  [GET, POST]
  requirements:
      ip_id: \d+
individual_plan_remove:
  path:   /individual-plan/remove/{ip_id}
  defaults: { _controller: BSUIRIndividualPlanBundle:IndividualPlans:remove }
  methods:  [GET]
  requirements:
      ip_id: \d+