<?php

namespace BSUIR\IndividualPlanBundle\Repository;

use BSUIR\IndividualPlanBundle\Entity\Professors;
use Doctrine\ORM\EntityRepository;

/**
 * EducationalMethodicalWork
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EducationalMethodicalWork extends EntityRepository
{
    public function findOneByIdAndProfessor($id, Professors $professors)
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('emw')
            ->from($this->getClassName(), 'emw')
            ->innerJoin('emw.individualPlan','ip')
            ->innerJoin('ip.professor','p')
            ->where('emw.id = :emw_id')
            ->andWhere('p.id = :p_id')
            ->setParameters(array(
                'emw_id' => $id,
                'p_id' => $professors->getId(),
            ))
            ->getQuery()
            ->getOneOrNullResult();
    }
}
