security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        BSUIR\IndividualPlanBundle\Entity\Professors:
            algorithm: sha512
            encode_as_base64: false
            iterations: 10

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        local:
            id: professors_provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            logout:
                path: professors_logout
                target: /
            form_login:
                login_path: professors_login
                check_path: professors_login_check
            anonymous: true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }