BSUIR\IndividualPlanBundle\Entity\Departments:
    type: entity
    table: departments
    oneToMany:
        professors:
            targetEntity: Professors
            mappedBy: department
            inversedBy: null
            joinColumn:
                id:
                referencedColumnName: professors
        disciplines:
            targetEntity: Disciplines
            mappedBy: department
            inversedBy: null
            joinColumn:
                id:
                referencedColumnName: disciplines
    manyToOne:
        faculty:
            targetEntity: Faculties
            mappedBy: null
            inversedBy: departments
            joinColumn:
                name: faculty
                referencedColumnName: id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    lifecycleCallbacks:
        prePersist: [ prePersist, preUpdate ]
        preUpdate: [ preUpdate ]