BSUIR\IndividualPlanBundle\Entity\Departments:
    type: entity
    table: departments
    oneToMany:
        professors:
            targetEntity: Professors
            mappedBy: department
            inversedBy: professors
            joinColumn:
                id:
                referencedColumnName: professors
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }
