BSUIR\IndividualPlanBundle\Entity\EducationWorkExecution:
    type: entity
    table: educational_work_execution
    repositoryClass: BSUIR\IndividualPlanBundle\Repository\EducationWorkExecution
    manyToOne:
        individualPlan:
            targetEntity: IndividualPlans
            mappedBy: null
            inversedBy: educationWorksExecution
            joinColumn:
                name: individual_plan
                referencedColumnName: id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        semester:
            type: integer
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
    uniqueConstraints:
        ip_semester:
            columns: individual_plan, semester
    lifecycleCallbacks:
        prePersist: [ prePersist, preUpdate ]
        preUpdate: [ preUpdate ]