BSUIR\IndividualPlanBundle\Entity\Faculties:
    type: entity
    table: faculties
    oneToMany:
        specialty:
            targetEntity: Specialty
            mappedBy: faculty
            invercedBy: null
            joinColumn:
                id:
                referencedColumnName: faculty
        departments:
            targetEntity: Departments
            mappedBy: faculty
            invercedBy: null
            joinColumn:
                id:
                referencedColumnName: faculty
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }
