BSUIR\IndividualPlanBundle\Entity\IndividualPlans:
    type: entity
    repositoryClass: BSUIR\IndividualPlanBundle\Repository\IndividualPlans
    table: individual_plans
    oneToOne:
        educationalMethodicalWork:
            targetEntity: EducationalMethodicalWork
            mappedBy: null
            cascade: ['remove']
            inversedBy: individualPlan
            joinColumn:
                name: educational_methodical_work
                referencedColumnName: id
                onDelete: SET NULL
        scientificWork:
            targetEntity: ScientificWork
            mappedBy: null
            cascade: ['remove']
            inversedBy: individualPlan
            joinColumn:
                name: scientific_work
                referencedColumnName: id
                onDelete: SET NULL
    manyToOne:
        professor:
            targetEntity: Professors
            mappedBy: null
            inversedBy: individualPlans
            joinColumn:
                name: professor
                referencedColumnName: id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdAt:
            type: datetimetz
        updatedAt:
            type: datetimetz
        session:
            type: integer
    lifecycleCallbacks:
        prePersist: [ prePersist, preUpdate ]
        preUpdate: [ preUpdate ]
