BSUIR\IndividualPlanBundle\Entity\OtherWork:
    type: entity
    table: other_work
    repositoryClass: BSUIR\IndividualPlanBundle\Repository\OtherWork
    oneToOne:
        individualPlan:
            targetEntity: IndividualPlans
            mappedBy: otherWork
    oneToMany:
        otherItems:
            targetEntity: OtherItems
            cascade: ['remove']
            mappedBy: otherWork
            inversedBy: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
    lifecycleCallbacks:
        prePersist: [ prePersist, preUpdate ]
        preUpdate: [ preUpdate ]

