BSUIR\IndividualPlanBundle\Entity\Professors:
    type: entity
    table: professors
    manyToOne:
        department:
            targetEntity: Departments
            mappedBy: professors
            inversedBy: professors
            joinColumn:
                name: department
                referencedColumnName: id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            length: 255
            column: first_name
        secondName:
            type: string
            length: 255
            column: second_name
        lastName:
            type: string
            length: 255
            column: last_name
        email:
            type: string
            length: 255
        password:
            type: string
            length: 255
        salt:
            type: string
            length: 255
        academicTitle:
            type: string
            length: 255
            column: academic_title
        scholasticDegree:
            type: string
            length: 255
            column: sholastic_degree
        competitionSelected:
            type: date
            column: competition_selected
    lifecycleCallbacks: {  }
