BSUIR\IndividualPlanBundle\Entity\ScientificItems:
    type: entity
    table: scientific_items
    repositoryClass: BSUIR\IndividualPlanBundle\Repository\ScientificItems
    manyToOne:
        scientificWork:
            targetEntity: ScientificWork
            mappedBy: null
            inversedBy: scientificItems
            joinColumn:
                name: scientific_work
                referencedColumnName: id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        workName:
            type: string
            length: 255
        startedAt:
            type: datetime
        finishedAt:
            type: datetime
        markFirst:
            type: integer
        markSecond:
            type: integer
        note:
            type: text
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
    lifecycleCallbacks:
        prePersist: [ prePersist, preUpdate ]
        preUpdate: [ preUpdate ]
