BSUIR\IndividualPlanBundle\Entity\ScientificWork:
    type: entity
    table: scientific_work
    repositoryClass: BSUIR\IndividualPlanBundle\Repository\ScientificWork
    oneToOne:
        individualPlan:
            targetEntity: IndividualPlans
            mappedBy: scientificWork
    oneToMany:
        scientificItems:
            targetEntity: ScientificItems
            cascade: ['remove']
            mappedBy: scientificWork
            inversedBy: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        topicName:
            type: string
            length: 255
        partName:
            type: string
            length: 255
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
    lifecycleCallbacks:
        prePersist: [ prePersist, preUpdate ]
        preUpdate: [ preUpdate ]

