BSUIR\IndividualPlanBundle\Entity\Specialty:
    type: entity
    table: specialty
    oneToMany:
        groups:
            targetEntity: Groups
            mappedBy: specialty
            inversedBy: null
            joinColumn:
                id:
                referencedColumnName: groups
    manyToOne:
        faculty:
            targetEntity: Faculties
            mappedBy: null
            inversedBy: specialty
            joinColumn:
                name: faculty
                referencedColumnName: id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }
